language: c

dist: focal

env:
  global:
   - secure: "qvRpkAmV7PRQHoUfjhykb5lkvMyMFAlNYh/1140ej/iHjDsO9bFpX2qxbfgAe8jaW8VBf4ly+VpjA9ByJHWol6/b+FwURa/yiFgNESxeYDUJz/dJCYyrgORH+t41bCwV8SEYZmpa3NJiDi4GkH8iojEi+dQYhWoN4uwEg81m45c="

matrix:
  include:
    - os: linux
      addons:
        sonarcloud:
          organization: "openomf"
        apt:
          packages:
            - gcc-9
            - cmake
            - cmake-data
            - libargtable2-dev
            - libcunit1-dev
            - libopenal-dev
            - libconfuse-dev
            - libenet-dev
            - libsdl2-dev
            - libxmp-dev
            - libpng-dev
      cache:
        directories:
          - '$HOME/.sonar/cache'
      after_script:
        - build-wrapper-linux-x86-64 --out-dir bw-output make
        - sonar-scanner
      env:
        - MATRIX_EVAL="CC=gcc-9"
    - os: linux
      addons:
        apt:
          packages:
            - gcc-10
            - cmake
            - cmake-data
            - libargtable2-dev
            - libcunit1-dev
            - libopenal-dev
            - libconfuse-dev
            - libenet-dev
            - libsdl2-dev
            - libxmp-dev
            - libpng-dev
      env:
        - MATRIX_EVAL="CC=gcc-10"
    - os: linux
      addons:
        apt:
          packages:
            - clang-10
            - cmake
            - cmake-data
            - libargtable2-dev
            - libcunit1-dev
            - libopenal-dev
            - libconfuse-dev
            - libenet-dev
            - libsdl2-dev
            - libxmp-dev
            - libpng-dev
      env:
        - MATRIX_EVAL="CC=clang-10"
    - os: linux
      addons:
        apt:
          packages:
            - clang-11
            - cmake
            - cmake-data
            - libargtable2-dev
            - libcunit1-dev
            - libopenal-dev
            - libconfuse-dev
            - libenet-dev
            - libsdl2-dev
            - libxmp-dev
            - libpng-dev
      env:
        - MATRIX_EVAL="CC=clang-11"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cd $TRAVIS_BUILD_DIR
  - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_TESTS=On -DUSE_TOOLS=On .
  - make
  - make test ARGS="-V"
  - make clean

notifications:
  email: false
