name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:

  # Run unittests on a recent version of clang
  # -----------------------------------------------------------------------------------------------
  unittest:
    name: Formatting Check, Unittest
    runs-on: ubuntu-24.04
    env:
      clang-version: '18'

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Install dependencies
      uses: Eeems-Org/apt-cache-action@v1.3
      with:
        packages: cmake cmake-data ninja-build libargtable2-dev libcunit1-dev
          libsdl2-mixer-dev libconfuse-dev libenet-dev libsdl2-dev libxmp-dev libpng-dev
          libepoxy-dev clang-${{ env.clang-version }} clang-tidy-${{ env.clang-version }}
          clang-format-${{ env.clang-version }} fd-find

    - name: Run clang-format style check
      run: |
        fdfind . -e .c -e .h -X clang-format-${{ env.clang-version }} --dry-run --Werror

    - name: Build tests
      run: |
        cmake -DCMAKE_C_COMPILER=clang-${{ env.clang-version }} \
              -DUSE_TIDY=On \
              -DUSE_TESTS=On \
              -DUSE_SANITIZERS=On \
              -DUSE_FATAL_SANITIZERS=On \
              -DUSE_TOOLS=On \
              -G "Ninja Multi-Config" \
              -S . -B build-test
        cmake --build build-test -j $(getconf _NPROCESSORS_ONLN)

    - name: Run tests
      run: |
        cd build-test
        ctest --verbose --output-on-failure

    - name: Get OMF2097 assets
      uses: ./.github/actions/assets

    - name: Extract omf 2097 assets
      run: unzip -j omf2097-assets.zip -d build-test/resources

    - name: Install pytest requirements
      run: |
        pipx install poetry
        poetry install

    - name: Run pytest tests
      run: ./run_pytest.sh build-test ./Debug/openomf

  # Build windows release artifacts with MSVC
  # -----------------------------------------------------------------------------------------------
  build_msvc:
    needs: [unittest]
    name: Build Windows ${{ matrix.config.arch }}
    runs-on: windows-latest
    strategy:
      matrix:
        config:
        - { arch: "x64", build_languages: "ON" }
        - { arch: "arm64", build_languages: "OFF" }
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Build MSVC binary
      uses: ./.github/actions/build_msvc
      with:
        arch: ${{ matrix.config.arch }}
        build_languages: ${{ matrix.config.build_languages }}


  # Build ubuntu package, release artifact
  # -----------------------------------------------------------------------------------------------
  build_ubuntu:
    needs: [unittest]
    name: Build ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Build Ubuntu binary
      uses: ./.github/actions/build_ubuntu

  # Build macos package, release artifact
  # -----------------------------------------------------------------------------------------------
  build_macos-arm:
    needs: [unittest]

    name: Build macos-14
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Get OpenOMF Version
      uses: ./.github/actions/version

    - name: Install Mac Dependencies
      run: |
        brew update
        brew install cmake argtable cunit sdl2_mixer confuse enet sdl2 libxmp libpng libepoxy miniupnpc libnatpmp

    - name: Generate Release
      run: |
        mkdir build-release && cd build-release
        cmake -DUSE_NATPMP=ON -DUSE_MINIUPNPC=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=release/usr ..
        make -j $(getconf _NPROCESSORS_ONLN)
        make -j $(getconf _NPROCESSORS_ONLN) install

    - name: Get OMF2097 assets
      uses: ./.github/actions/assets

    - name: Extract omf 2097 assets
      run: unzip -j omf2097-assets.zip -d build-release/release/usr/share/games/openomf

    - name: Generate ZIP package
      run: |
        cd build-release/release
        zip -r ${GITHUB_WORKSPACE}/openomf_${{ env.OPENOMF_VERSION }}_macos14_arm.zip .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openomf_${{ env.OPENOMF_VERSION }}_macos14_arm
        path: openomf_${{ env.OPENOMF_VERSION }}_macos14_arm.zip
        if-no-files-found: error

  # Build MinGW, just so we know it still compiles
  # -----------------------------------------------------------------------------------------------
  check_mingw:
    needs: [unittest]

    name: Check MinGW-w64 cross
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Install apt Dependencies
      uses: Eeems-Org/apt-cache-action@v1.3
      with:
        packages: mingw-w64 unzip wine64 wine
    - name: Install Dependencies
      run: |
        wget -q https://github.com/omf2097/openomf-win-build/archive/refs/heads/main.zip
        unzip -q main.zip && rm main.zip

    - name: Build MinGW-w64
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=release \
              --toolchain "cmake-scripts/mingw-w64-toolchain.cmake" \
              -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/openomf-win-build-main/" \
              -DCMAKE_INCLUDE_PATH="${GITHUB_WORKSPACE}/openomf-win-build-main/include/" \
              -DCMAKE_LIBRARY_PATH="${GITHUB_WORKSPACE}/openomf-win-build-main/lib/" \
              -DCMAKE_FIND_ROOT_PATH="${GITHUB_WORKSPACE}/openomf-win-build-main/" \
              -DBUILD_LANGUAGES=OFF \
              -DUSE_NATPMP=ON \
              -DUSE_MINIUPNPC=ON \
              -S . -B build
        cmake --build build -j $(getconf _NPROCESSORS_ONLN)


  # Create a "latest" release
  # -----------------------------------------------------------------------------------------------
  make_release:
    needs: [check_mingw, build_macos-arm, build_ubuntu, build_msvc]
    if: github.ref == 'refs/heads/master'

    name: Make "latest" release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Get OpenOMF Version
      uses: ./.github/actions/version

    - uses: actions/download-artifact@v4
      with:
        path: artifacts/

    - name: Advance tag
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}          
        script: |
          try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "tags/latest"
              })
          } catch (e) {
            console.log("The 'latest' tag doesn't exist yet", e)
          }
          try {
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "refs/tags/latest",
                sha: context.sha
              })
          } catch (e) {
            console.log("Unable to create 'latest' tag", e)
          }

    - name: Organize release artifacts
      run: |
        mkdir upload
        mkdir windows_all

        combine_windows() {
            if [ "$#" -ne 2 ]; then
              echo "wrong argc to combine_windows"
              exit 1
            fi
            unzip -d windows_all -o -u "$1"
            rm "$1"
            if [ "$2" != "openomf.exe" ]; then
                mv "windows_all/openomf/openomf.exe" "windows_all/openomf/$2"
            fi
        }
        combine_windows artifacts/openomf_*_windows_msvc_arm64/*.zip openomf_arm64.exe
        combine_windows artifacts/openomf_*_windows_msvc_x64/*.zip openomf.exe

        cd windows_all/
        zip -r ${GITHUB_WORKSPACE}/upload/openomf_${{ env.OPENOMF_VERSION }}_windows.zip *
        cd ..

        shopt -s globstar
        for file in artifacts/**; do
          if [ -f "$file" ]; then
            cp "$file" "${GITHUB_WORKSPACE}/upload/"
          fi
        done

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "upload/*"
        body: "Latest release from master. Note that this is autogenerated release, and should only be used for testing purposes."
        name: Latest
        tag: latest
        allowUpdates: true
        prerelease: true
        removeArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
